[instrument_a]
epic = "CC.D.CL.USS.IP"
fmp_symbol = "CLUSD"
name = "Oil - US Crude"
expiry = "DFB"
currency_code = "GBP"

[instrument_b]
epic = "CC.D.HO.USS.IP"
fmp_symbol = "HOUSD"
name = "Heating Oil"
expiry = "DFB"
currency_code = "GBP"

[strategy]
notional_trade_size = 3000
model_update_interval_business_days = 7
entry_stds = 2.0
limit_stds = 0.25
stop_stds = 4.5
poll_interval_seconds = 15
warmup_minutes = 1440
max_fit_lookback_days = 30
