[instrument_a]
epic = "CC.D.LCO.USS.IP"
fmp_symbol = "BZUSD"
name = "Oil - Brent Crude"
expiry = "DFB"
currency_code = "GBP"

[instrument_b]
epic = "CC.D.RB.USS.IP"
fmp_symbol = "RBUSD"
name = "No Lead Gasoline"
expiry = "DFB"
currency_code = "GBP"

[strategy]
notional_trade_size = 2000
model_update_interval_business_days = 7
entry_stds = 1.25
limit_stds = 0.0
stop_stds = 5.5
poll_interval_seconds = 15
warmup_minutes = 1440
max_fit_lookback_days = 30
